# Generated by Django 3.2.10 on 2022-04-20 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20220420_1911'),
    ]

    operations = [
        migrations.CreateModel(
            name='auth_token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=300)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.userpayer')),
            ],
        ),
    ]
