# Generated by Django 3.2.10 on 2022-04-20 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auth_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acount_number', models.CharField(max_length=14)),
                ('bank', models.IntegerField()),
                ('branch', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.CharField(default='9000000', max_length=9)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.userpayer')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'PENDING'), (2, 'FINISHED'), (3, 'REJECTED')], default=1)),
                ('acount_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.account')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.userpayer')),
            ],
        ),
    ]
