# Generated by Django 3.2.10 on 2022-04-28 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20220426_1816'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auth_token',
            old_name='id_user',
            new_name='user_payer',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='user_id',
            new_name='user_payer',
        ),
        migrations.RenameField(
            model_name='wallet',
            old_name='user_id',
            new_name='user',
        ),
    ]
