# Generated by Django 3.2.10 on 2022-04-28 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20220428_1705'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='user',
            new_name='user_payer',
        ),
    ]
