# Generated by Django 3.2.10 on 2022-04-28 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_rename_user_wallet_user_payer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='acount_number',
            new_name='account_number',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='acount_id',
            new_name='account_id',
        ),
    ]
